added storage
lpdalle/backend pull request #3
Opened 2022-12-12 17:52 UTC by vosart

2022-12-12 20:00 UTC, vppuzakov requested changes

2022-12-12 20:00 UTC, vppuzakov commented on .gitignore
> +test.py
А что test.py в gitignore? - дай посмотреть на него

2022-12-12 20:00 UTC, vppuzakov commented on storage.py
> +        self.storage: dict[str, dict[str]] = {}
🔴 несоответствует тип и реально хранимые значения

`dict[str, Users]` хранится же

2022-12-12 20:00 UTC, vppuzakov commented on storage.py
> +class Users:
🔴 Переименуй в ед. числе датакласс сущности

2022-12-12 20:00 UTC, vppuzakov commented on storage.py
> +    def get_all(self) -> list[dict[str]]:
🔴 Возвращаемый тип задан неверно
да, список - но не словарей же, а чего?
и даже если бы были словари - их нельзя указывать в виде dict[str] - там должно быть два типа (ключ и значение)

2022-12-12 20:00 UTC, vppuzakov commented on storage.py
> +    def get_by_uid(self, uid: str) -> dict:
🔴 словарь нельзя указывать без задания типов ключа и значения

2022-12-12 20:00 UTC, vppuzakov commented on storage.py
> +            return asdict(self.storage[uid])
🔴 Пусть сторадж возвращает датакласс, а не словарь. Твой сторадж не должен думать о том где его используют и что там должен быть словарь. Твой сторадж существует только ради для решения своих целей. Он оперирует датаклассами - значит не надо выходить за рамки датаклассов.

2022-12-12 20:00 UTC, vppuzakov commented on storage.py
> +        return
return лишний, можешь вернуть bool пока
return True - удалось удалить, return False - не удалось - ну какую то целостность типов сохранить нужно

функция возвращает bool - целостно

2022-12-12 20:00 UTC, vppuzakov commented on users.py
> +users = UserStorage()
👍

2022-12-12 20:00 UTC, vppuzakov commented on users.py
> +    return users.get_all()
🔴 не забудь преобразовать в список словарей

2022-12-12 20:00 UTC, vppuzakov commented on users.py
> +        return users.get_by_uid(uid)
словарь

2022-12-12 20:00 UTC, vppuzakov commented on users.py
> +    users.add(login=user_login, email=user_email)
👍

2022-12-12 20:00 UTC, vppuzakov commented on users.py
> +    users.update(uid=uid, login=user_login, email=user_email)
💡 метод update должен вернуть User уже измененный - нет необходимости запрашивать его второй раз

2022-12-12 20:00 UTC, vppuzakov commented on users.py
> +        users.delete(uid)
Метод delete стораджа должен сам вернуть было ли удаление или не найден пользователь - нет необходимости повторно спрашивать есть ли пользователь

2022-12-12 20:17 UTC, vosart commented on .gitignore
> +test.py
там ничего интересного) теперь буду ipython юзать

2022-12-12 20:46 UTC, vosart commented on users.py
> +    return users.get_all()
оно преобразуется в storage.py

2022-12-13 05:07 UTC, vppuzakov requested changes
Еще совсем чуть-чуть

2022-12-13 05:07 UTC, vppuzakov commented on storage.py
> +        if self.storage.get(uid):
🔴 А если не найден - возвращаем None - это надо явно прописать, также и в тайп хинтах возврата

```python
def get_by_uid(self, uid: str) -> User | None:
    ....
```

2022-12-13 05:07 UTC, vppuzakov commented on storage.py
> +        self.storage[uid] = User(uid=uid, login=login, email=email)
💡 лучше было бы не присваивать нового, а найти старого и заменить у него поля - сделай так

2022-12-13 05:07 UTC, vppuzakov commented on users.py
> +    return users.get_all()
Явно бы привел к списку словарей

дзен пайтон: явное лучше неявного

2022-12-13 05:07 UTC, vppuzakov commented on users.py
> +    return asdict(users.update(uid=uid, login=user_login, email=user_email)), 201
🔴 слишком сложная строчка вышла - разбей на несколько, сначала получи обновленного пользователя, потом верни ответ

2022-12-13 05:07 UTC, vppuzakov commented on users.py
> +    if users.delete(uid):
👍

2022-12-13 11:03 UTC, vppuzakov approved these changes

2022-12-13 11:05 UTC, merged