add custom errors and generations schema
lpdalle/backend pull request #9
Opened 2022-12-26 21:54 UTC by vosart

2022-12-26 22:15 UTC, vosart commented
чтобы обрабатывать ошибку, если логин не найден, пришлось тип uid в ошибках поставить на str

2022-12-27 05:25 UTC, vppuzakov approved these changes

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/__main__.py
> +    return 'Empty data', 400
🔴 надо вернуть json

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/errors.py
> +        self.reason = reason
🔴 self.reason не нужен - он уже присваивается в родительском конструкторе

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/generations/gen_storage.py
> +        uid = None
🔴 это лишнее, его можно просто не передавать в конструктор Generations

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/generations/gen_storage.py
> +            raise NotFoundError('Generation not found', str(uid))
👍

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/generations/generations.py
> +    except BadRequestError:
🔴 тут что-то странное - перехватываешь и бросаешь ее же - наверно забыл удалить

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/generations/generations.py
> +    except IntegrityError:
🔴 Почему тут остался IntegrityError от алхимии - view не должна ничего знать про ошибки алхимии

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/db_storage.py
> +            raise NotFoundError('users', str(uid))
👍

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/db_storage.py
> +            raise NotFoundError('users', login)
👍

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/db_storage.py
> +            raise ConflictError('users', uid)
👍

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/db_storage.py
> +            raise NotFoundError('users', str(uid))
👍

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/users.py
> +    except BadRequestError:
🔴 тоже странное - удаляй

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/users.py
> +        raise BadRequestError('Empty user data!')
👍

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/users.py
> +    except IntegrityError:
🔴 ошибка алхимии

2022-12-27 05:25 UTC, vppuzakov commented on lpdalle/user/users.py
> +    except BadRequestError:
🔴 ну ты уже понял )

2022-12-27 05:26 UTC, vppuzakov requested changes
по ошибкам в основном доработай

2022-12-27 11:13 UTC, vppuzakov approved these changes

2022-12-27 11:15 UTC, merged